### ISSUE TITLE
old gsis ids found in current play_by_play data for download

### ISSUE THREAD

**Issue by henninghe** [nflverse/nflfastR-data#54]
Hi there,

I just stumbled over the fact that the current play_by_play data for download suddenly contains the old style gsis ids for players (e.g. 00-0023459) instead of the new long ones (e.g. 32013030-2d30-3032-3334-35395dc60da5). 

Is this intended?

**Comment by mrcaseb** [comment]
That's indeed intended behavior. We don't really see a reason not to do it as all roster data use the old GSIS ID format. 

However, if you want pbp data with IDs in the new format, you can build the data by running something like 

```r
ids <- nflfastR::fast_scraper_schedules(2020)
pbp <- nflfastR::build_nflfastR_pbp(ids, decode = FALSE)
```

**Comment by henninghe** [comment]
Ok, thank You for the fast reply. Knowing this I will adapt my code to rely on GSIS IDs and the nflfastR-roster data in the future.
I really appreciate Your work to provide this project to all of us.
